name: Main CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/main_ci.yml'
      - 'cmake/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'conanfile.py'
      - 'vcpkg.json'
  pull_request:
    branches: [ main, feature/* ]
  workflow_dispatch:

env:
  VCPKG_COMMIT_ID: faed44dfa013088fe1910908a8a65887622f412f

jobs:
  build-and-test-vcpkg:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - debug
          - release
        runtime:
          - all
          - flatrim
          - ae
          - se
          - vr
        compiler:
          - msvc
          - clang-cl
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10.0
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: true

      - name: Build
        uses: lukka/run-cmake@v10.0
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/main/CMakeLists.txt
          configurePreset: build-${{ matrix.build-type }}-${{ matrix.compiler }}-vcpkg-${{ matrix.runtime }}
          buildPreset: ${{ matrix.build-type }}-${{ matrix.compiler }}-vcpkg-${{ matrix.runtime }}

      - name: Unit tests
        timeout-minutes: 5
        working-directory: ${{ github.workspace }}/main/build/${{ matrix.build-type }}-${{ matrix.compiler }}-vcpkg-${{ matrix.runtime }}
        run: .\CommonLibSSETests.exe
  build-and-test-conan:
    runs-on: windows-latest
    env:
      BUILD_CONTEXT: |
        {
          "build": {
            "debug": "Debug",
            "release": "Release"
          },
          "runtime": {
            "all": {
              "ae": "True",
              "se": "True",
              "vr": "True"
            },
            "flatrim": {
              "ae": "True",
              "se": "True",
              "vr": "False"
            },
            "ae": {
              "ae": "True",
              "se": "False",
              "vr": "False"
            },
            "se": {
              "ae": "False",
              "se": "True",
              "vr": "False"
            },
            "vr": {
              "ae": "False",
              "se": "False",
              "vr": "True"
            }
          }
        }
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - debug
          - release
        runtime:
          - all
          - flatrim
          - ae
          - se
          - vr
        compiler:
          - msvc
          - clang-cl
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Run Conan
        working-directory: ${{ github.workspace }}/main
        run: conan install --build=missing -s build_type=${{ fromJSON(env.BUILD_CONTEXT).build[matrix.build-type] }} -o commonlibsse-ng:testing=True -o commonlibsse-ng:with_ae=${{ fromJSON(env.BUILD_TYPE).runtime[matrix.runtime].ae }} -o commonlibsse-ng:with_se=${{ fromJSON(env.BUILD_TYPE).runtime[matrix.runtime].se }} -o commonlibsse-ng:with_vr=${{ fromJSON(env.BUILD_TYPE).runtime[matrix.runtime].vr }} .

      - name: Build with CMake
        uses: lukka/run-cmake@v10.0
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/main/CMakeLists.txt
          configurePreset: build-${{ matrix.build-type }}-${{ matrix.compiler }}-conan-${{ matrix.runtime }}
          buildPreset: ${{ matrix.build-type }}-${{ matrix.compiler }}-conan-${{ matrix.runtime }}

      - name: Build with Conan
        working-directory: ${{ github.workspace }}/main
        run: conan build .

      - name: Unit tests
        timeout-minutes: 5
        working-directory: ${{ github.workspace }}/main/build/${{ matrix.build-type }}-${{ matrix.compiler }}-conan-${{ matrix.runtime }}
        run: .\CommonLibSSETests.exe

      - name: Create Conan Package
        working-directory: ${{ github.workspace }}/main
        run: conan create -s build_type=${{ fromJSON(env.BUILD_CONTEXT).build[matrix.build-type] }} -o commonlibsse-ng:with_ae=${{ fromJSON(env.BUILD_TYPE).runtime[matrix.runtime].ae }} -o commonlibsse-ng:with_se=${{ fromJSON(env.BUILD_TYPE).runtime[matrix.runtime].se }} -o commonlibsse-ng:with_vr=${{ fromJSON(env.BUILD_TYPE).runtime[matrix.runtime].vr }} .
