name: Main CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/main_ci.yml'
      - 'cmake/**'
      - 'include/**'
      - 'src/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
  pull_request:
    branches: [ main, feature/* ]
  workflow_dispatch:

env:
  VCPKG_COMMIT_ID: b98afc9f1192becb2f447cee485ce36ba111f9f6

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - Debug
          - Release
        runtime:
          - All
          - Flatrim
          - AE
          - SE
          - VR
        compiler:
          - MSVC
          - ClangCL
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10.0
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: true

      - name: Build
        uses: lukka/run-cmake@v10.0
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/main/CMakeLists.txt
          configurePreset: ${{ matrix.build-type }}-${{ matrix.runtime }}-${{ matrix.compiler }}
          buildPreset: ${{ matrix.build-type }}-${{ matrix.runtime }}-${{ matrix.compiler }}

      - name: Cache
        uses: actions/cache@v2
        with:
          path: main
          key: ${{ matrix.build-type }}-${{ matrix.runtime }}-${{ matrix.compiler }}-${{ github.sha }}
        if: ${{ matrix.build-type == 'Debug' && matrix.runtime == 'All' && matrix.compiler == 'MSVC' }}

  unit-tests:
    runs-on: windows-latest
    needs:
      - build
    steps:
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: main
          key: Debug-All-MSVC-${{ github.sha }}

      - name: Run unit tests
        working-directory: ${{ github.workspace }}/main
        run: ctest --preset Unit-Tests
